const { contextBridge, ipcRenderer } = require("electron");

function subscribe(channel, callback) {
  const handler = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
}

contextBridge.exposeInMainWorld("api", {
  openVideos: () => ipcRenderer.invoke("dialog:openVideos"),
  openExcel: () => ipcRenderer.invoke("dialog:openExcel"),
  selectOutputDir: () => ipcRenderer.invoke("dialog:selectOutputDir"),
  restoreSessionPaths: (payload) => ipcRenderer.invoke("session:restorePaths", payload),
  getVideoInfo: (path) => ipcRenderer.invoke("fs:getVideoInfo", path),
  getVideoInfoBatch: (paths) => ipcRenderer.invoke("fs:getVideoInfoBatch", paths),
  readExcel: (path) => ipcRenderer.invoke("fs:readExcel", path),
  saveExcelDialog: (defaultName) => ipcRenderer.invoke("dialog:saveExcel", defaultName),
  writeExcel: (path, base64Data) => ipcRenderer.invoke("fs:writeExcel", path, base64Data),
  startProcessing: (jobs) => ipcRenderer.invoke("process:start", jobs),
  cancelProcessing: () => ipcRenderer.invoke("process:cancel"),
  exportProcessingLogs: (text) => ipcRenderer.invoke("process:exportLogs", text),
  openPath: (path) => ipcRenderer.invoke("shell:openPath", path),
  showItemInFolder: (path) => ipcRenderer.invoke("shell:showItemInFolder", path),
  saveProject: (payload) => ipcRenderer.invoke("project:save", payload),
  loadProject: () => ipcRenderer.invoke("project:load"),
  loadProjectFromPath: (path) => ipcRenderer.invoke("project:loadFromPath", path),
  listPresets: () => ipcRenderer.invoke("presets:list"),
  savePreset: (name, jsonStr) => ipcRenderer.invoke("presets:save", name, jsonStr),
  deletePreset: (filename) => ipcRenderer.invoke("presets:delete", filename),
  loadSettings: () => ipcRenderer.invoke("settings:load"),
  saveSettings: (partial) => ipcRenderer.invoke("settings:save", partial),
  setWindowTheme: (theme) => ipcRenderer.invoke("window:setTheme", theme),
  getBatchCapacity: (opts) => ipcRenderer.invoke("system:getBatchCapacity", opts),
  listRecent: () => ipcRenderer.invoke("recent:list"),
  addRecent: (entry) => ipcRenderer.invoke("recent:add", entry),
  removeRecent: (path) => ipcRenderer.invoke("recent:remove", path),
  listExecutionHistory: () => ipcRenderer.invoke("executionHistory:list"),
  saveExecutionHistory: (history) => ipcRenderer.invoke("executionHistory:save", history),
  clearExecutionHistory: () => ipcRenderer.invoke("executionHistory:clear"),
  checkForUpdates: () => ipcRenderer.invoke("updater:check"),
  downloadUpdate: (opts) => ipcRenderer.invoke("updater:download", opts),
  installUpdate: () => ipcRenderer.invoke("updater:install"),
  getUpdaterSnapshot: () => ipcRenderer.invoke("updater:getSnapshot"),
  openExternal: (url) => ipcRenderer.invoke("shell:openExternal", url),
  fetchPetManifest: () => ipcRenderer.invoke("petdex:fetchManifest"),
  listInstalledPets: () => ipcRenderer.invoke("petdex:listInstalled"),
  installPet: (entry) => ipcRenderer.invoke("petdex:install", entry),
  uninstallPet: (slug) => ipcRenderer.invoke("petdex:uninstall", slug),
  getPetSpritesheet: (slug) => ipcRenderer.invoke("petdex:getSpritesheet", slug),
  getBundledSpritesheet: (slug) => ipcRenderer.invoke("petdex:getBundledSpritesheet", slug),
  openPetOverlay: (position) => ipcRenderer.invoke("petOverlay:open", position),
  closePetOverlay: () => ipcRenderer.invoke("petOverlay:close"),
  togglePetOverlay: (position) => ipcRenderer.invoke("petOverlay:toggle", position),
  syncPetOverlayState: (state) => ipcRenderer.invoke("petOverlay:sync", state),
  getPetOverlayState: () => ipcRenderer.invoke("petOverlay:getState"),
  popInPetOverlay: () => ipcRenderer.invoke("petOverlay:popIn"),
  dragPetOverlayBy: (delta) => ipcRenderer.invoke("petOverlay:dragBy", delta),
  onPetOverlayState: (cb) => subscribe("petOverlay:state", cb),
  onPetOverlayEvent: (cb) => subscribe("petOverlay:event", cb),
  onUpdaterEvent: (cb) => subscribe("updater:event", cb),
  readImage: (path) => ipcRenderer.invoke("image:read", path),
  pickImage: () => ipcRenderer.invoke("image:pick"),
  resolveDroppedPaths: (paths) => ipcRenderer.invoke("fs:resolveDroppedPaths", paths),
  getThumbnail: (path) => ipcRenderer.invoke("video:thumbnail", path),
  getThumbnailBatch: (paths) => ipcRenderer.invoke("video:thumbnailBatch", paths),
  renderPreviewFrame: (payload) => ipcRenderer.invoke("video:renderPreviewFrame", payload),

  onProgress: (cb) => subscribe("process:progress", cb),
  onJobProgress: (cb) => subscribe("process:jobProgress", cb),
  onComplete: (cb) => subscribe("process:complete", cb),
  onSummary: (cb) => subscribe("process:summary", cb),
  onJobError: (cb) => subscribe("process:jobError", cb),
  onJobCancelled: (cb) => subscribe("process:jobCancelled", cb),
  onFinished: (cb) => subscribe("process:finished", cb),
  onRunStarted: (cb) => subscribe("process:runStarted", cb),
  onError: (cb) => subscribe("process:error", cb),
  onLog: (cb) => subscribe("process:log", cb),
});
