// @ts-check
/* ── Region normalization ─────────────────────────────────────────────── */

import { TEXT_STYLE_DEFAULTS } from "./text-style";

export function normalizeRegion(region, videoWidth, videoHeight) {
  if (!region) return null;
  if (!videoWidth || !videoHeight) return null;
  return {
    x: region.x / videoWidth,
    y: region.y / videoHeight,
    w: region.w / videoWidth,
    h: region.h / videoHeight,
  };
}

export function denormalizeRegion(region, videoWidth, videoHeight) {
  if (!region) return null;
  if (!videoWidth || !videoHeight) return null;
  return {
    x: Math.round(region.x * videoWidth),
    y: Math.round(region.y * videoHeight),
    w: Math.round(region.w * videoWidth),
    h: Math.round(region.h * videoHeight),
  };
}

const NORM_EPS = 1e-6;

export function isNormalizedRegion(region) {
  if (!region) return false;
  // Epsilon on edge sums so float noise near the frame border (e.g. 0.81+0.2)
  // is still treated as normalized 0..1 coords, not mis-detected as pixels.
  return (
    region.x >= -NORM_EPS &&
    region.y >= -NORM_EPS &&
    region.w >= 0 &&
    region.h >= 0 &&
    region.x <= 1 + NORM_EPS &&
    region.y <= 1 + NORM_EPS &&
    region.w <= 1 + NORM_EPS &&
    region.h <= 1 + NORM_EPS &&
    region.x + region.w <= 1 + NORM_EPS &&
    region.y + region.h <= 1 + NORM_EPS
  );
}

function clampUnitRegion(region) {
  return {
    x: Math.min(1, Math.max(0, region.x)),
    y: Math.min(1, Math.max(0, region.y)),
    w: Math.min(1, Math.max(0, region.w)),
    h: Math.min(1, Math.max(0, region.h)),
  };
}

export function ensureNormalized(region, videoWidth, videoHeight) {
  if (!region) return null;
  if (isNormalizedRegion(region)) {
    // Preserve identity when already a clean unit square; clamp float edge noise.
    const clean =
      region.x >= 0 && region.y >= 0 && region.x + region.w <= 1 && region.y + region.h <= 1;
    return clean ? region : clampUnitRegion(region);
  }
  // Ambiguous 0..1-looking coords that failed the sum check: keep as
  // normalized instead of dividing by video size (which collapses the box).
  const maybeNorm =
    region.x >= 0 &&
    region.y >= 0 &&
    region.w >= 0 &&
    region.h >= 0 &&
    region.x <= 1 &&
    region.y <= 1 &&
    region.w <= 1 &&
    region.h <= 1;
  if (maybeNorm) return region;
  return normalizeRegion(region, videoWidth, videoHeight);
}

/* ── Shared types for Beru ───────────────────────────────────────────── */

let _idCounter = 0;
export function uid() {
  _idCounter = (_idCounter + 1) % 1_000_000;
  return `${Date.now().toString(36)}-${_idCounter.toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

export const FONT_FAMILIES = [
  "Arial",
  "Arial Black",
  "Bahnschrift",
  "Calibri",
  "Cambria",
  "Candara",
  "Consolas",
  "Courier New",
  "Franklin Gothic Medium",
  "Georgia",
  "Impact",
  "Segoe UI",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
];

export const FONT_WEIGHTS = [
  { value: 100, label: "Thin" },
  { value: 300, label: "Light" },
  { value: 400, label: "Regular" },
  { value: 500, label: "Medium" },
  { value: 600, label: "Semi" },
  { value: 700, label: "Bold" },
  { value: 900, label: "Black" },
];

export const TEXT_ALIGNS = [
  { value: "left", label: "⇤" },
  { value: "center", label: "↔" },
  { value: "right", label: "⇥" },
];

export const DELOGO_METHODS = [
  {
    id: "temporal",
    label: "Temporal",
    description:
      "Mediana entre N fotogramas: ideal para logos estáticos sobre video en movimiento. Indistinguible.",
  },
  {
    id: "mirror",
    label: "Espejo",
    description:
      "Refleja un lado de la región sobre el otro. Perfecto para fondos uniformes (cielo, pared, suelo).",
  },
  {
    id: "mosaic",
    label: "Mosaico",
    description: "Pixelado grueso. Útil para rostros, matrículas e identificadores sensibles.",
  },
  {
    id: "inpaint",
    label: "Inpaint",
    description:
      "Interpolación 4-direcciones del filtro delogo de FFmpeg. Rápido, resultado decente.",
  },
  {
    id: "blur",
    label: "Desenfoque",
    description: "Box blur. Suaviza la región pero deja una mancha visible.",
  },
  {
    id: "fill",
    label: "Relleno",
    description: "Cubre con un color sólido. Solo para casos muy específicos.",
  },
  {
    id: "cover",
    label: "Cubierta",
    description: "Superpone una imagen del usuario limitada al rectángulo del logo.",
  },
];

export const MIRROR_SIDES = [
  { id: "right", label: "← Reflejar desde derecha" },
  { id: "left", label: "Reflejar desde izquierda →" },
  { id: "bottom", label: "↑ Reflejar desde abajo" },
  { id: "top", label: "Reflejar desde arriba ↓" },
];

export const TEXT_STYLE_PRESETS = [
  {
    id: "plain",
    name: "Sin estilo",
    previewBg: "var(--bg-elevated)",
    fontFamily: "Arial",
    fontColor: "white",
    fontWeight: 400,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "ot-code",
    name: "Código OT",
    previewBg: "#505050",
    fontFamily: "Arial",
    fontColor: "#d7d7d7",
    fontWeight: 400,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 1,
    borderColor: "#6b6b6b",
    textShadowEnabled: true,
    textShadowColor: "#2b2b2b",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "soft-gray",
    name: "Gris suave",
    previewBg: "#5b5960",
    fontFamily: "Arial",
    fontColor: "#d2d0d4",
    fontWeight: 300,
    letterSpacing: 1,
    textOpacity: 0.92,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#4b4850",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "caption",
    name: "Caption",
    previewBg: "#202020",
    fontFamily: "Segoe UI",
    fontColor: "white",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: true,
    bgColor: "black",
    bgOpacity: 0.68,
    boxBorderWidth: 5,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "outline-white",
    name: "Blanco stroke",
    previewBg: "#2f2f2f",
    fontFamily: "Arial",
    fontColor: "white",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 3,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "soft-shadow",
    name: "Sombra suave",
    previewBg: "#2a2a2a",
    fontFamily: "Segoe UI",
    fontColor: "white",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 3,
    textShadowOffsetY: 3,
  },
  {
    id: "deep-shadow",
    name: "Sombra fuerte",
    previewBg: "#242424",
    fontFamily: "Segoe UI",
    fontColor: "white",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 3,
    textShadowOffsetY: 3,
  },
  {
    id: "neon-yellow",
    name: "Amarillo neon",
    previewBg: "#2b2b2b",
    fontFamily: "Segoe UI",
    fontColor: "#ffff00",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 3,
    textShadowOffsetY: 3,
  },
  {
    id: "red-pop",
    name: "Rojo pop",
    previewBg: "#3a3a3a",
    fontFamily: "Segoe UI",
    fontColor: "#ff3333",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "white",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "orange-pop",
    name: "Naranja pop",
    previewBg: "#4b4b4b",
    fontFamily: "Segoe UI",
    fontColor: "#ff7a1a",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "white",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "blue-pop",
    name: "Azul pop",
    previewBg: "#606060",
    fontFamily: "Segoe UI",
    fontColor: "#168dff",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "white",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "green-pop",
    name: "Verde pop",
    previewBg: "#222222",
    fontFamily: "Segoe UI",
    fontColor: "#00e843",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "ink",
    name: "Tinta",
    previewBg: "#8c8c8c",
    fontFamily: "Arial",
    fontColor: "#111111",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "silver-block",
    name: "Plata",
    previewBg: "#9e9e9e",
    fontFamily: "Segoe UI",
    fontColor: "white",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#777777",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "yellow-block",
    name: "Bloque amarillo",
    previewBg: "#ffe600",
    fontFamily: "Segoe UI",
    fontColor: "black",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: true,
    bgColor: "#ffe600",
    bgOpacity: 1,
    boxBorderWidth: 6,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  {
    id: "violet-block",
    name: "Bloque violeta",
    previewBg: "#7c3aed",
    fontFamily: "Segoe UI",
    fontColor: "white",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: true,
    bgColor: "#7c3aed",
    bgOpacity: 1,
    boxBorderWidth: 6,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 2,
    textShadowOffsetY: 2,
  },
  // ── Additional presets (Apple / broadcast-inspired) ────────────────
  {
    id: "cinema",
    name: "Cinema",
    previewBg: "#1c1c1e",
    fontFamily: "Segoe UI",
    fontColor: "#f5f5f7",
    fontWeight: 500,
    letterSpacing: 0.5,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowOffsetX: 1,
    textShadowOffsetY: 2,
  },
  {
    id: "lower-third",
    name: "Lower third",
    previewBg: "#0a0a0c",
    fontFamily: "Segoe UI",
    fontColor: "#ffffff",
    fontWeight: 600,
    letterSpacing: 0.2,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: true,
    bgColor: "#000000",
    bgOpacity: 0.55,
    boxBorderWidth: 8,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "thin-ghost",
    name: "Ghost",
    previewBg: "#2c2c2e",
    fontFamily: "Segoe UI",
    fontColor: "#ffffff",
    fontWeight: 300,
    letterSpacing: 1.2,
    textOpacity: 0.78,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "gold",
    name: "Oro",
    previewBg: "#2a2418",
    fontFamily: "Georgia",
    fontColor: "#f0d48a",
    fontWeight: 600,
    letterSpacing: 0.4,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#3a2e12",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "cyan",
    name: "Cian",
    previewBg: "#0f1c22",
    fontFamily: "Segoe UI",
    fontColor: "#64d2ff",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#063246",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "magenta",
    name: "Magenta",
    previewBg: "#24141f",
    fontFamily: "Segoe UI",
    fontColor: "#ff6bcb",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#4a1038",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "outline-dark",
    name: "Stroke oscuro",
    previewBg: "#e5e5ea",
    fontFamily: "Arial",
    fontColor: "#1c1c1e",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "#ffffff",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "italic-soft",
    name: "Itálica suave",
    previewBg: "#3a3a3c",
    fontFamily: "Georgia",
    fontColor: "#e5e5ea",
    fontWeight: 400,
    letterSpacing: 0.3,
    textOpacity: 0.95,
    bold: false,
    italic: true,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#1c1c1e",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "mono-tag",
    name: "Mono tag",
    previewBg: "#1e1e20",
    fontFamily: "Consolas",
    fontColor: "#d1d1d6",
    fontWeight: 500,
    letterSpacing: 0.6,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: true,
    bgColor: "#2c2c2e",
    bgOpacity: 0.92,
    boxBorderWidth: 5,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "rose-block",
    name: "Bloque rosa",
    previewBg: "#ff375f",
    fontFamily: "Segoe UI",
    fontColor: "#ffffff",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: true,
    bgColor: "#ff375f",
    bgOpacity: 1,
    boxBorderWidth: 6,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "teal-block",
    name: "Bloque teal",
    previewBg: "#30b0c7",
    fontFamily: "Segoe UI",
    fontColor: "#ffffff",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: true,
    bgColor: "#30b0c7",
    bgOpacity: 1,
    boxBorderWidth: 6,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "alert-bar",
    name: "Alerta",
    previewBg: "#ff3b30",
    fontFamily: "Segoe UI",
    fontColor: "#ffffff",
    fontWeight: 700,
    letterSpacing: 0.4,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: true,
    bgColor: "#ff3b30",
    bgOpacity: 0.95,
    boxBorderWidth: 7,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "snow",
    name: "Nieve",
    previewBg: "#3a3a3c",
    fontFamily: "Arial",
    fontColor: "#ffffff",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 2,
    borderColor: "#1c1c1e",
    textShadowEnabled: true,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffsetX: 0,
    textShadowOffsetY: 1,
  },
  {
    id: "mint",
    name: "Menta",
    previewBg: "#163028",
    fontFamily: "Segoe UI",
    fontColor: "#63e6be",
    fontWeight: 600,
    letterSpacing: 0,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: false,
    bgColor: "black",
    bgOpacity: 0,
    boxBorderWidth: 4,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: true,
    textShadowColor: "#0b1f19",
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  {
    id: "amber-block",
    name: "Bloque ámbar",
    previewBg: "#ff9f0a",
    fontFamily: "Segoe UI",
    fontColor: "#1c1c1e",
    fontWeight: 700,
    letterSpacing: 0,
    textOpacity: 1,
    bold: true,
    italic: false,
    bgEnabled: true,
    bgColor: "#ff9f0a",
    bgOpacity: 1,
    boxBorderWidth: 6,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  {
    id: "glass",
    name: "Cristal",
    previewBg: "#1a1a1c",
    fontFamily: "Segoe UI",
    fontColor: "#f2f2f7",
    fontWeight: 500,
    letterSpacing: 0.2,
    textOpacity: 1,
    bold: false,
    italic: false,
    bgEnabled: true,
    bgColor: "#3a3a3c",
    bgOpacity: 0.42,
    boxBorderWidth: 7,
    borderWidth: 0,
    borderColor: "black",
    textShadowEnabled: false,
    textShadowColor: "black",
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
];

/* ── Plain objects / shapes (no classes) ───────────────────────────── */

export function createOperation(overrides = {}) {
  return {
    id: uid(),
    mode: "blur",
    region: null,
    blurStrength: 20,
    delogoMethod: "temporal",
    delogoFillColor: "black",
    delogoFillOpacity: 1,
    delogoImagePath: "",
    startTime: null,
    endTime: null,
    text: "",
    batchRegionId: null,
    ...TEXT_STYLE_DEFAULTS,
    imagePath: "",
    imageOpacity: 1,
    ...overrides,
  };
}

export function createQueueItem(overrides = {}) {
  return {
    path: "",
    src: "",
    filename: "",
    width: 0,
    height: 0,
    /** Resolution at first successful import probe — used for export. */
    sourceWidth: 0,
    sourceHeight: 0,
    duration: 0,
    videoCodec: "",
    pixFmt: "yuv420p",
    frameRate: 0,
    audioCodec: "",
    audioChannels: 0,
    operations: [],
    status: "idle",
    progress: 0,
    eta: null,
    speed: null,
    error: null,
    customOutputName: "",
    thumbnail: null,
    ...overrides,
  };
}
